export const DeFiInteractorModuleAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_avatar", type: "address", internalType: "address" },
      { name: "_owner", type: "address", internalType: "address" },
      { name: "_authorizedOracle", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEFAULT_MAX_SPENDING_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_WINDOW_DURATION",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFI_EXECUTE_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFI_TRANSFER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "absoluteMaxSpendingBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acquiredBalance",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowedAddresses",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedOracle",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "avatar",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchUpdate",
    inputs: [
      { name: "subAccount", type: "address", internalType: "address" },
      { name: "newAllowance", type: "uint256", internalType: "uint256" },
      { name: "tokens", type: "address[]", internalType: "address[]" },
      { name: "balances", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeOnProtocol",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeOnProtocolWithValue",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getAcquiredBalance",
    inputs: [
      { name: "subAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSafeValue",
    inputs: [],
    outputs: [
      { name: "totalValueUSD", type: "uint256", internalType: "uint256" },
      { name: "lastUpdated", type: "uint256", internalType: "uint256" },
      { name: "updateCount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSpendingAllowance",
    inputs: [{ name: "subAccount", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubAccountLimits",
    inputs: [{ name: "subAccount", type: "address", internalType: "address" }],
    outputs: [
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "maxSpendingUSD", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubaccountCount",
    inputs: [{ name: "roleId", type: "uint16", internalType: "uint16" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubaccountsByRole",
    inputs: [{ name: "roleId", type: "uint16", internalType: "uint16" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenBalances",
    inputs: [{ name: "tokens", type: "address[]", internalType: "address[]" }],
    outputs: [
      { name: "balances", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "member", type: "address", internalType: "address" },
      { name: "roleId", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "member", type: "address", internalType: "address" },
      { name: "roleId", type: "uint16", internalType: "uint16" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastOracleUpdate",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxOracleAge",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxPriceFeedAge",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxSafeValueAge",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolParsers",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "", type: "address", internalType: "contract ICalldataParser" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerParser",
    inputs: [
      { name: "protocol", type: "address", internalType: "address" },
      { name: "parser", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerSelector",
    inputs: [
      { name: "selector", type: "bytes4", internalType: "bytes4" },
      {
        name: "opType",
        type: "uint8",
        internalType: "enum DeFiInteractorModule.OperationType",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeRole",
    inputs: [
      { name: "member", type: "address", internalType: "address" },
      { name: "roleId", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "safeValue",
    inputs: [],
    outputs: [
      { name: "totalValueUSD", type: "uint256", internalType: "uint256" },
      { name: "lastUpdated", type: "uint256", internalType: "uint256" },
      { name: "updateCount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "selectorType",
    inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum DeFiInteractorModule.OperationType",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAbsoluteMaxSpendingBps",
    inputs: [{ name: "newMaxBps", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAllowedAddresses",
    inputs: [
      { name: "subAccount", type: "address", internalType: "address" },
      { name: "targets", type: "address[]", internalType: "address[]" },
      { name: "allowed", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAuthorizedOracle",
    inputs: [{ name: "newOracle", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAvatar",
    inputs: [{ name: "_avatar", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSubAccountLimits",
    inputs: [
      { name: "subAccount", type: "address", internalType: "address" },
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "maxSpendingUSD", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTarget",
    inputs: [{ name: "_target", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTokenPriceFeed",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "priceFeed", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTokenPriceFeeds",
    inputs: [
      { name: "tokens", type: "address[]", internalType: "address[]" },
      { name: "priceFeeds", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "spendingAllowance",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "subAccountLimits",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "maxSpendingUSD", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
      { name: "isConfigured", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "subAccountRoles",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint16", internalType: "uint16" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "subaccounts",
    inputs: [
      { name: "", type: "uint16", internalType: "uint16" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "target",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenPriceFeeds",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract AggregatorV3Interface",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "_newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unregisterSelector",
    inputs: [{ name: "selector", type: "bytes4", internalType: "bytes4" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateAcquiredBalance",
    inputs: [
      { name: "subAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "newBalance", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSafeValue",
    inputs: [
      { name: "totalValueUSD", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSpendingAllowance",
    inputs: [
      { name: "subAccount", type: "address", internalType: "address" },
      { name: "newAllowance", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AcquiredBalanceUpdated",
    inputs: [
      {
        name: "subAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newBalance",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AllowedAddressesSet",
    inputs: [
      {
        name: "subAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "targets",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
      { name: "allowed", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AvatarSet",
    inputs: [
      {
        name: "previousAvatar",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAvatar",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EmergencyPaused",
    inputs: [
      { name: "by", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EmergencyUnpaused",
    inputs: [
      { name: "by", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OracleUpdated",
    inputs: [
      {
        name: "oldOracle",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOracle",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ParserRegistered",
    inputs: [
      {
        name: "protocol",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "parser",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolExecution",
    inputs: [
      {
        name: "subAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "target",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "opType",
        type: "uint8",
        indexed: false,
        internalType: "enum DeFiInteractorModule.OperationType",
      },
      {
        name: "tokensIn",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
      {
        name: "amountsIn",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "tokensOut",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
      {
        name: "amountsOut",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "spendingCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAssigned",
    inputs: [
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "roleId", type: "uint16", indexed: true, internalType: "uint16" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "roleId", type: "uint16", indexed: true, internalType: "uint16" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SafeValueUpdated",
    inputs: [
      {
        name: "totalValueUSD",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "updateCount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SelectorRegistered",
    inputs: [
      {
        name: "selector",
        type: "bytes4",
        indexed: true,
        internalType: "bytes4",
      },
      {
        name: "opType",
        type: "uint8",
        indexed: false,
        internalType: "enum DeFiInteractorModule.OperationType",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SelectorUnregistered",
    inputs: [
      {
        name: "selector",
        type: "bytes4",
        indexed: true,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SpendingAllowanceUpdated",
    inputs: [
      {
        name: "subAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAllowance",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SubAccountLimitsSet",
    inputs: [
      {
        name: "subAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "maxSpendingBps",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxSpendingUSD",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "windowDuration",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TargetSet",
    inputs: [
      {
        name: "previousTarget",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newTarget",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferExecuted",
    inputs: [
      {
        name: "subAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "spendingCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AddressNotAllowed", inputs: [] },
  { type: "error", name: "ApprovalExceedsLimit", inputs: [] },
  { type: "error", name: "ApprovalFailed", inputs: [] },
  {
    type: "error",
    name: "CannotBeOracle",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "CannotBeSubaccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "CannotRegisterParserForCoreAddress",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "CannotRegisterUnknown", inputs: [] },
  {
    type: "error",
    name: "CannotWhitelistCoreAddress",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "EnforcedPause", inputs: [] },
  {
    type: "error",
    name: "ExceedsAbsoluteMaxSpending",
    inputs: [
      { name: "requested", type: "uint256", internalType: "uint256" },
      { name: "maximum", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "ExceedsMaxBps", inputs: [] },
  { type: "error", name: "ExceedsSpendingLimit", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "InvalidAddress", inputs: [] },
  { type: "error", name: "InvalidLimitConfiguration", inputs: [] },
  { type: "error", name: "InvalidOracleAddress", inputs: [] },
  { type: "error", name: "InvalidPrice", inputs: [] },
  { type: "error", name: "InvalidPriceFeed", inputs: [] },
  {
    type: "error",
    name: "InvalidRecipient",
    inputs: [
      { name: "recipient", type: "address", internalType: "address" },
      { name: "expected", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "LengthMismatch", inputs: [] },
  { type: "error", name: "ModuleTransactionFailed", inputs: [] },
  {
    type: "error",
    name: "NoParserRegistered",
    inputs: [{ name: "target", type: "address", internalType: "address" }],
  },
  { type: "error", name: "NoPriceFeedSet", inputs: [] },
  { type: "error", name: "OnlyAuthorizedOracle", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SpenderNotAllowed", inputs: [] },
  { type: "error", name: "StaleOracleData", inputs: [] },
  { type: "error", name: "StalePortfolioValue", inputs: [] },
  { type: "error", name: "StalePriceFeed", inputs: [] },
  { type: "error", name: "TransactionFailed", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  {
    type: "error",
    name: "UnknownSelector",
    inputs: [{ name: "selector", type: "bytes4", internalType: "bytes4" }],
  },
] as const;
