export const PresetRegistryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_initialOwner", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPreset",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "roleId", type: "uint16", internalType: "uint16" },
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
      {
        name: "allowedProtocols",
        type: "address[]",
        internalType: "address[]",
      },
      { name: "parserProtocols", type: "address[]", internalType: "address[]" },
      { name: "parserAddresses", type: "address[]", internalType: "address[]" },
      { name: "selectors", type: "bytes4[]", internalType: "bytes4[]" },
      { name: "selectorTypes", type: "uint8[]", internalType: "uint8[]" },
    ],
    outputs: [{ name: "presetId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPreset",
    inputs: [{ name: "presetId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "roleId", type: "uint16", internalType: "uint16" },
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPresetFull",
    inputs: [{ name: "presetId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "roleId", type: "uint16", internalType: "uint16" },
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
      {
        name: "allowedProtocols",
        type: "address[]",
        internalType: "address[]",
      },
      { name: "parserProtocols", type: "address[]", internalType: "address[]" },
      { name: "parserAddresses", type: "address[]", internalType: "address[]" },
      { name: "selectors", type: "bytes4[]", internalType: "bytes4[]" },
      { name: "selectorTypes", type: "uint8[]", internalType: "uint8[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPresetProtocols",
    inputs: [{ name: "presetId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "presetCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "presetExists",
    inputs: [{ name: "presetId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePreset",
    inputs: [
      { name: "presetId", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
      { name: "roleId", type: "uint16", internalType: "uint16" },
      { name: "maxSpendingBps", type: "uint256", internalType: "uint256" },
      { name: "windowDuration", type: "uint256", internalType: "uint256" },
      {
        name: "allowedProtocols",
        type: "address[]",
        internalType: "address[]",
      },
      { name: "parserProtocols", type: "address[]", internalType: "address[]" },
      { name: "parserAddresses", type: "address[]", internalType: "address[]" },
      { name: "selectors", type: "bytes4[]", internalType: "bytes4[]" },
      { name: "selectorTypes", type: "uint8[]", internalType: "uint8[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PresetCreated",
    inputs: [
      {
        name: "presetId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "name", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PresetUpdated",
    inputs: [
      {
        name: "presetId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "name", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  { type: "error", name: "ArrayLengthMismatch", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "PresetNotFound",
    inputs: [{ name: "presetId", type: "uint256", internalType: "uint256" }],
  },
] as const;
